### ISSUE TITLE
"Issueベース開発"レビュー依頼

### ISSUE THREAD

**Issue by hase-n323** [hase-n323/love_your_home#26]
### 実装予定の機能

- [ ] Three.jsを使用したシュミレーション機能
- [ ] sorceryを使用したユーザー機能
- [ ] i18nの日本語化
- [ ] フラッシュメッセージの設定
- [ ] デコレーターの導入
- [ ] タイトルの動的化
- [ ] ブックマーク機能
- [ ] ブックマークボタンのajax化
- [ ] プロフィール編集機能
- [ ] パスワードリセット機能
- [ ] 関連動画（youtube）表示
- [ ] twitterシェアボタンの設置
- [ ] 楽天APIを使用した機能

### 必要なページ

- [ ] トップページ
- [ ] プライバシーポリシーページ
- [ ] 利用規約ページ
- [ ] シュミレーション(mainpage)ページ
- [ ] ログインページ
- [ ] サインアップページ
- [ ] パスワードリセット申請ページ
- [ ] ブックマーク一覧ページ
- [ ] プロフィールページ
- [ ] プロフィール編集ページ

**Comment by hase-n323** [comment]
RUNTEQ レビュー担当者様

いつもお世話になっております。
issueのレビューをお願い致します。
お忙しいところ大変申し訳ありませんがよろしくお願い致します。

54_a　長谷川

**Comment by beppumasaki** [comment]
エントリーポイントは5以下で設定できる粒度まで細かくするといいと思います！
下記の二つは時間かかる想定であれば、もう少し細かくしてもいいかもしれません！
https://github.com/hase-n323/love_your_home/issues/5
https://github.com/hase-n323/love_your_home/issues/25

再検討してエントリーポイントの変更があれば、修正お願いします！
